ProdDB:
  type: "postgresql"
  dsn: "postgres://postgres:Mypass123@localhost:5432?sslmode=disable"
  max_open_connections: 10
  max_idle_connections: 10
  max_connection_idle_time: 30s
  push_frequency: 1s
  pull_frequency: 1s

PaymentGateway:
  type: "stripe"
  receive-route: "stripe-test-account-webhooks"
  api_key: "XXX"
  endpoint_secret: "XXX"
  push_frequency: 5s
  pull_frequency: 5s

DataWarehouse:
  type: "snowflake"
  dsn: "snowflake://user:password@account/warehouse"
  max_open_connections: 2
  max_idle_connections: 2
  max_connection_idle_time: 60s
  push_frequency: 10s
