package formatters

import (
	"database/sql"

	"github.com/sqlpipe/sqlpipe/internal/engine/transfers/formatters/shared"
)

var MssqlCreateFormatters = map[string]func(column *sql.ColumnType, terminator string) (string, error){
	"SQL_UNKNOWN_TYPE":    shared.NTextCreateFormatter,
	"SQL_CHAR":            shared.NTextCreateFormatter,
	"SQL_NUMERIC":         shared.DecimalCreateFormatter,
	"SQL_DECIMAL":         shared.DecimalCreateFormatter,
	"SQL_INTEGER":         shared.IntCreateFormatter,
	"SQL_SMALLINT":        shared.SmallIntCreateFormatter,
	"SQL_FLOAT":           shared.FloatCreateFormatter,
	"SQL_REAL":            shared.FloatCreateFormatter,
	"SQL_DOUBLE":          shared.FloatCreateFormatter,
	"SQL_DATETIME":        shared.Datetime2CreateFormatter,
	"SQL_TIME":            shared.TimeCreateFormatter,
	"SQL_VARCHAR":         shared.NTextCreateFormatter,
	"SQL_TYPE_DATE":       shared.DateCreateFormatter,
	"SQL_TYPE_TIME":       shared.TimeCreateFormatter,
	"SQL_TYPE_TIMESTAMP":  shared.Datetime2CreateFormatter,
	"SQL_TIMESTAMP":       shared.Datetime2CreateFormatter,
	"SQL_LONGVARCHAR":     shared.NTextCreateFormatter,
	"SQL_BINARY":          shared.NTextCreateFormatter,
	"SQL_VARBINARY":       shared.NTextCreateFormatter,
	"SQL_LONGVARBINARY":   shared.NTextCreateFormatter,
	"SQL_BIGINT":          shared.BigIntCreateFormatter,
	"SQL_TINYINT":         shared.SmallIntCreateFormatter,
	"SQL_BIT":             shared.BitCreateFormatter,
	"SQL_WCHAR":           shared.NTextCreateFormatter,
	"SQL_WVARCHAR":        shared.NTextCreateFormatter,
	"SQL_WLONGVARCHAR":    shared.NTextCreateFormatter,
	"SQL_GUID":            shared.UniqueIdentifierCreateFormatter,
	"SQL_SIGNED_OFFSET":   shared.NTextCreateFormatter,
	"SQL_UNSIGNED_OFFSET": shared.NTextCreateFormatter,
	"SQL_SS_XML":          shared.XmlCreateFormatter,
	"SQL_SS_TIME2":        shared.TimeCreateFormatter,
}

var MssqlMidStringValFormatters = map[string]func(value interface{}) (string, error){
	"SQL_UNKNOWN_TYPE":    shared.CastToBytesCastToStringPrintQuotedXcommaXnull,
	"SQL_CHAR":            shared.CastToBytesCastToStringPrintQuotedXcommaXnull,
	"SQL_NUMERIC":         shared.RawXcommaXnull,
	"SQL_DECIMAL":         shared.RawXcommaXnull,
	"SQL_INTEGER":         shared.RawXcommaXnull,
	"SQL_SMALLINT":        shared.RawXcommaXnull,
	"SQL_FLOAT":           shared.RawXcommaXnull,
	"SQL_REAL":            shared.RawXcommaXnull,
	"SQL_DOUBLE":          shared.RawXcommaXnull,
	"SQL_DATETIME":        shared.CastToTimeFormatToTimetampStringXcommaXnull,
	"SQL_TIME":            shared.CastToTimeFormatToTimeStringXcommaXnull,
	"SQL_VARCHAR":         shared.CastToBytesCastToStringPrintQuotedXcommaXnull,
	"SQL_TYPE_DATE":       shared.CastToTimeFormatToDateStringXcommaXnull,
	"SQL_TYPE_TIME":       shared.CastToTimeFormatToTimeStringXcommaXnull,
	"SQL_TYPE_TIMESTAMP":  shared.CastToTimeFormatToTimetampStringXcommaXnull,
	"SQL_TIMESTAMP":       shared.CastToTimeFormatToTimetampStringXcommaXnull,
	"SQL_LONGVARCHAR":     shared.CastToBytesCastToStringPrintQuotedXcommaXnull,
	"SQL_BINARY":          shared.CastToBytesCastToStringPrintQuotedHexXcommaXnull,
	"SQL_VARBINARY":       shared.CastToBytesCastToStringPrintQuotedHexXcommaXnull,
	"SQL_LONGVARBINARY":   shared.CastToBytesCastToStringPrintQuotedHexXcommaXnull,
	"SQL_BIGINT":          shared.RawXcommaXnull,
	"SQL_TINYINT":         shared.RawXcommaXnull,
	"SQL_BIT":             shared.CastToBoolWriteBinaryEquivalentXcommaXnull,
	"SQL_WCHAR":           shared.CastToBytesCastToStringPrintQuotedXcommaXnull,
	"SQL_WVARCHAR":        shared.CastToBytesCastToStringPrintQuotedXcommaXnull,
	"SQL_WLONGVARCHAR":    shared.CastToBytesCastToStringPrintQuotedXcommaXnull,
	"SQL_GUID":            shared.QuotedXcommaXnull,
	"SQL_SIGNED_OFFSET":   shared.CastToBytesCastToStringPrintQuotedXcommaXnull,
	"SQL_UNSIGNED_OFFSET": shared.CastToBytesCastToStringPrintQuotedXcommaXnull,
	"SQL_SS_XML":          shared.CastToBytesCastToStringPrintQuotedXcommaXnull,
	"SQL_SS_TIME2":        shared.CastToBytesCastToStringPrintQuotedXcommaXnull,
}

var MssqlEndStringValFormatters = map[string]func(value interface{}) (string, error){
	"SQL_UNKNOWN_TYPE":    shared.CastToBytesCastToStringPrintQuotedXparenthesisXnull,
	"SQL_CHAR":            shared.CastToBytesCastToStringPrintQuotedXparenthesisXnull,
	"SQL_NUMERIC":         shared.RawXparenthesisXnull,
	"SQL_DECIMAL":         shared.RawXparenthesisXnull,
	"SQL_INTEGER":         shared.RawXparenthesisXnull,
	"SQL_SMALLINT":        shared.RawXparenthesisXnull,
	"SQL_FLOAT":           shared.RawXparenthesisXnull,
	"SQL_REAL":            shared.RawXparenthesisXnull,
	"SQL_DOUBLE":          shared.RawXparenthesisXnull,
	"SQL_DATETIME":        shared.CastToTimeFormatToTimetampStringXparenthesisXnull,
	"SQL_TIME":            shared.CastToTimeFormatToTimeStringXparenthesisXnull,
	"SQL_VARCHAR":         shared.CastToBytesCastToStringPrintQuotedXparenthesisXnull,
	"SQL_TYPE_DATE":       shared.CastToTimeFormatToDateStringXparenthesisXnull,
	"SQL_TYPE_TIME":       shared.CastToTimeFormatToTimeStringXparenthesisXnull,
	"SQL_TYPE_TIMESTAMP":  shared.CastToTimeFormatToTimetampStringXparenthesisXnull,
	"SQL_TIMESTAMP":       shared.CastToTimeFormatToTimetampStringXparenthesisXnull,
	"SQL_LONGVARCHAR":     shared.CastToBytesCastToStringPrintQuotedXparenthesisXnull,
	"SQL_BINARY":          shared.CastToBytesCastToStringPrintQuotedHexXparenthesisXnull,
	"SQL_VARBINARY":       shared.CastToBytesCastToStringPrintQuotedHexXparenthesisXnull,
	"SQL_LONGVARBINARY":   shared.CastToBytesCastToStringPrintQuotedHexXparenthesisXnull,
	"SQL_BIGINT":          shared.RawXparenthesisXnull,
	"SQL_TINYINT":         shared.RawXparenthesisXnull,
	"SQL_BIT":             shared.CastToBoolWriteBinaryEquivalentXparenthesisXnull,
	"SQL_WCHAR":           shared.CastToBytesCastToStringPrintQuotedXparenthesisXnull,
	"SQL_WVARCHAR":        shared.CastToBytesCastToStringPrintQuotedXparenthesisXnull,
	"SQL_WLONGVARCHAR":    shared.CastToBytesCastToStringPrintQuotedXparenthesisXnull,
	"SQL_GUID":            shared.QuotedXparenthesisXnull,
	"SQL_SIGNED_OFFSET":   shared.CastToBytesCastToStringPrintQuotedXparenthesisXnull,
	"SQL_UNSIGNED_OFFSET": shared.CastToBytesCastToStringPrintQuotedXparenthesisXnull,
	"SQL_SS_XML":          shared.CastToBytesCastToStringPrintQuotedXparenthesisXnull,
	"SQL_SS_TIME2":        shared.CastToBytesCastToStringPrintQuotedXparenthesisXnull,
}
