package formatters

import (
	"database/sql"

	"github.com/sqlpipe/sqlpipe/internal/engine/transfers/formatters/shared"
)

var PostgresqlCreateFormatters = map[string]func(column *sql.ColumnType, terminator string) (string, error){
	"SQL_UNKNOWN_TYPE":    shared.TextCreateFormatter,
	"SQL_CHAR":            shared.TextCreateFormatter,
	"SQL_NUMERIC":         shared.NumericCreateFormatter,
	"SQL_DECIMAL":         shared.NumericCreateFormatter,
	"SQL_INTEGER":         shared.IntCreateFormatter,
	"SQL_SMALLINT":        shared.SmallIntCreateFormatter,
	"SQL_FLOAT":           shared.DoubleCreateFormatter,
	"SQL_REAL":            shared.DoubleCreateFormatter,
	"SQL_DOUBLE":          shared.DoubleCreateFormatter,
	"SQL_DATETIME":        shared.TimestampCreateFormatter,
	"SQL_TIME":            shared.TimeCreateFormatter,
	"SQL_VARCHAR":         shared.TextCreateFormatter,
	"SQL_TYPE_DATE":       shared.DateCreateFormatter,
	"SQL_TYPE_TIME":       shared.TimeCreateFormatter,
	"SQL_TYPE_TIMESTAMP":  shared.TimestampCreateFormatter,
	"SQL_TIMESTAMP":       shared.TimestampCreateFormatter,
	"SQL_LONGVARCHAR":     shared.TextCreateFormatter,
	"SQL_BINARY":          shared.ByteaCreateFormatter,
	"SQL_VARBINARY":       shared.ByteaCreateFormatter,
	"SQL_LONGVARBINARY":   shared.ByteaCreateFormatter,
	"SQL_BIGINT":          shared.BigIntCreateFormatter,
	"SQL_TINYINT":         shared.SmallIntCreateFormatter,
	"SQL_BIT":             shared.BoolCreateFormatter,
	"SQL_WCHAR":           shared.TextCreateFormatter,
	"SQL_WVARCHAR":        shared.TextCreateFormatter,
	"SQL_WLONGVARCHAR":    shared.TextCreateFormatter,
	"SQL_GUID":            shared.UuidCreateFormatter,
	"SQL_SIGNED_OFFSET":   shared.TextCreateFormatter,
	"SQL_UNSIGNED_OFFSET": shared.TextCreateFormatter,
	"SQL_SS_XML":          shared.XmlCreateFormatter,
	"SQL_SS_TIME2":        shared.TimeCreateFormatter,
}

var PostgresqlMidStringValFormatters = map[string]func(value interface{}) (string, error){
	"SQL_UNKNOWN_TYPE":    shared.RawXcommaXnull,
	"SQL_CHAR":            shared.RawXcommaXnull,
	"SQL_NUMERIC":         shared.RawXcommaXnull,
	"SQL_DECIMAL":         shared.RawXcommaXnull,
	"SQL_INTEGER":         shared.RawXcommaXnull,
	"SQL_SMALLINT":        shared.RawXcommaXnull,
	"SQL_FLOAT":           shared.RawXcommaXnull,
	"SQL_REAL":            shared.RawXcommaXnull,
	"SQL_DOUBLE":          shared.RawXcommaXnull,
	"SQL_DATETIME":        shared.RawXcommaXnull,
	"SQL_TIME":            shared.RawXcommaXnull,
	"SQL_VARCHAR":         shared.CastToBytesCastToStringPrintQuotedXcommaXnull,
	"SQL_TYPE_DATE":       shared.CastToTimeFormatToDateStringXcommaXnull,
	"SQL_TYPE_TIME":       shared.CastToTimeFormatToTimeStringXcommaXnull,
	"SQL_TYPE_TIMESTAMP":  shared.CastToTimeFormatToTimetampStringXcommaXnull,
	"SQL_TIMESTAMP":       shared.RawXcommaXnull,
	"SQL_LONGVARCHAR":     shared.RawXcommaXnull,
	"SQL_BINARY":          shared.RawXcommaXnull,
	"SQL_VARBINARY":       shared.RawXcommaXnull,
	"SQL_LONGVARBINARY":   shared.CastToBytesCastToStringPrintQuotedHexXcommaXnull,
	"SQL_BIGINT":          shared.RawXcommaXnull,
	"SQL_TINYINT":         shared.RawXcommaXnull,
	"SQL_BIT":             shared.CastToBoolWriteBinaryEquivalentXcommaXnull,
	"SQL_WCHAR":           shared.CastToBytesCastToStringPrintQuotedXcommaXnull,
	"SQL_WVARCHAR":        shared.CastToBytesCastToStringPrintQuotedXcommaXnull,
	"SQL_WLONGVARCHAR":    shared.CastToBytesCastToStringPrintQuotedXcommaXnull,
	"SQL_GUID":            shared.QuotedXcommaXnull,
	"SQL_SIGNED_OFFSET":   shared.RawXcommaXnull,
	"SQL_UNSIGNED_OFFSET": shared.RawXcommaXnull,
	"SQL_SS_XML":          shared.RawXcommaXnull,
	"SQL_SS_TIME2":        shared.RawXcommaXnull,
}

var PostgresqlEndStringValFormatters = map[string]func(value interface{}) (string, error){
	"SQL_UNKNOWN_TYPE":    shared.RawXparenthesisXnull,
	"SQL_CHAR":            shared.RawXparenthesisXnull,
	"SQL_NUMERIC":         shared.RawXparenthesisXnull,
	"SQL_DECIMAL":         shared.RawXparenthesisXnull,
	"SQL_INTEGER":         shared.RawXparenthesisXnull,
	"SQL_SMALLINT":        shared.RawXparenthesisXnull,
	"SQL_FLOAT":           shared.RawXparenthesisXnull,
	"SQL_REAL":            shared.RawXparenthesisXnull,
	"SQL_DOUBLE":          shared.RawXparenthesisXnull,
	"SQL_DATETIME":        shared.RawXparenthesisXnull,
	"SQL_TIME":            shared.RawXparenthesisXnull,
	"SQL_VARCHAR":         shared.CastToBytesCastToStringPrintQuotedXparenthesisXnull,
	"SQL_TYPE_DATE":       shared.CastToTimeFormatToDateStringXparenthesisXnull,
	"SQL_TYPE_TIME":       shared.CastToTimeFormatToTimeStringXparenthesisXnull,
	"SQL_TYPE_TIMESTAMP":  shared.CastToTimeFormatToTimetampStringXparenthesisXnull,
	"SQL_TIMESTAMP":       shared.RawXparenthesisXnull,
	"SQL_LONGVARCHAR":     shared.RawXparenthesisXnull,
	"SQL_BINARY":          shared.RawXparenthesisXnull,
	"SQL_VARBINARY":       shared.RawXparenthesisXnull,
	"SQL_LONGVARBINARY":   shared.CastToBytesCastToStringPrintQuotedHexXparenthesisXnull,
	"SQL_BIGINT":          shared.RawXparenthesisXnull,
	"SQL_TINYINT":         shared.RawXparenthesisXnull,
	"SQL_BIT":             shared.CastToBoolWriteBinaryEquivalentXparenthesisXnull,
	"SQL_WCHAR":           shared.CastToBytesCastToStringPrintQuotedXparenthesisXnull,
	"SQL_WVARCHAR":        shared.CastToBytesCastToStringPrintQuotedXparenthesisXnull,
	"SQL_WLONGVARCHAR":    shared.CastToBytesCastToStringPrintQuotedXparenthesisXnull,
	"SQL_GUID":            shared.QuotedXparenthesisXnull,
	"SQL_SIGNED_OFFSET":   shared.RawXparenthesisXnull,
	"SQL_UNSIGNED_OFFSET": shared.RawXparenthesisXnull,
	"SQL_SS_XML":          shared.RawXparenthesisXnull,
	"SQL_SS_TIME2":        shared.RawXparenthesisXnull,
}
